* timelist
  Blocks everything except sites on whitelists. Heeds storage.managed settings.

[[https://chrome.google.com/webstore/detail/jsguardian/iplmogomomicjamihdpekpgcefblbnfk][https://img.shields.io/chrome-web-store/v/iplmogomomicjamihdpekpgcefblbnfk.svg]]
** Versions
*** 0.4.x
**** Lacked Firefox installation
*** 0.3.2
**** Failed
     - to reload if cache was initialized too early
*** 0.3.1
**** Failed
     - to list the block set if the URL contained a =&=
*** 0.3.0
**** Lacked
     - time-based blocking
     - multiple block sets
*** 0.2.1
**** Failed
     to open vanilla chrome:newtab on Google Chrome
*** 0.2.0
**** Lacked 
     - real settings support
     - blockpage showing which page was blocked
** Managed Policy
   To modify the list of allowed sites, you need to set a managed
   policy. See
   https://www.chromium.org/administrators/configuring-policy-for-extensions.

   On Linux, f.ex. you can add the following to your
   =/etc/chromium/policies/managed/config.json= (or another file in
   that directory).

   #+BEGIN_SRC js
     "3rdparty": {
       "extensions": {
         "iplmogomomicjamihdpekpgcefblbnfk": {
           "whitelist": "(google|youtube\\.com)",
           "blocks": [ {
             "whitelist": "google",
             "starttime": "0800",
             "endtime": "1500"
           } ]
         }
       }
     }
   #+END_SRC

   This would generally allow only addresses containing /google/ and
   /youtube/.

   From 08:00 to 15:00, /youtube/ would be blocked as well.
